FROM python:3.9.1

# RUN apt-get install wget
# RUN pip install pandas sqlalchemy psycopg2

# WORKDIR /app
# COPY ingest_data.py ingest_data.py 

# ENTRYPOINT [ "python", "ingest_data.py" ]
ENTRYPOINT [ "bash" ]


# Q2
# root@f48d1a7ddac3:/# pip list
# Package    Version
# ---------- -------
# pip        21.0.1
# setuptools 53.0.0
# wheel      0.36.2